# Generated by Django 5.1.5 on 2025-05-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoAnalyst", "0003_analysisreport_snapshot_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisreport",
            name="language",
            field=models.CharField(
                choices=[
                    ("zh-CN", "简体中文"),
                    ("en-US", "English"),
                    ("ja-JP", "日本語"),
                    ("ko-KR", "한국어"),
                ],
                default="zh-CN",
                max_length=10,
                verbose_name="报告语言",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("zh-CN", "简体中文"),
                    ("en-US", "English"),
                    ("ja-JP", "日本語"),
                    ("ko-KR", "한국어"),
                ],
                default="zh-CN",
                max_length=10,
                verbose_name="语言偏好",
            ),
        ),
    ]
