# Generated by Django 4.2.10 on 2025-05-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoAnalyst", "0004_analysisreport_language_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisreport",
            name="language",
            field=models.CharField(
                choices=[
                    ("zh-CN", "简体中文"),
                    ("en-US", "English"),
                    ("ja-JP", "日本語"),
                    ("ko-KR", "한국어"),
                ],
                default="en-US",
                max_length=10,
                verbose_name="报告语言",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("zh-CN", "简体中文"),
                    ("en-US", "English"),
                    ("ja-JP", "日本語"),
                    ("ko-KR", "한국어"),
                ],
                default="en-US",
                max_length=10,
                verbose_name="语言偏好",
            ),
        ),
    ]
