# Generated by Django 4.2.10 on 2025-07-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoAnalyst', '0004_remove_token_chain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markettype',
            name='name',
            field=models.CharField(choices=[('crypto', 'Cryptocurrency'), ('stock', 'US Stock'), ('china', 'China A-Share')], max_length=20, unique=True),
        ),
    ]
