# Generated by Django 4.2.10 on 2025-05-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoAnalyst", "0005_alter_analysisreport_language_alter_user_language"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MarketData",
        ),
    ]
