# Generated by Django 4.2.10 on 2025-07-05 10:45
# Data migration to initialize China A-Share market data

from django.db import migrations


def create_china_market_data(apps, schema_editor):
    """Create China A-Share market type and exchanges"""
    MarketType = apps.get_model('CryptoAnalyst', 'MarketType')
    Exchange = apps.get_model('CryptoAnalyst', 'Exchange')

    # Create China A-Share market type
    china_market, created = MarketType.objects.get_or_create(
        name='china',
        defaults={'display_name': 'China A-Share'}
    )

    if created:
        print("Created China A-Share market type")

    # Create China stock exchanges
    sse_exchange, created = Exchange.objects.get_or_create(
        name='sse',
        defaults={
            'display_name': 'Shanghai Stock Exchange',
            'market_type': china_market
        }
    )

    if created:
        print("Created Shanghai Stock Exchange")

    szse_exchange, created = Exchange.objects.get_or_create(
        name='szse',
        defaults={
            'display_name': 'Shenzhen Stock Exchange',
            'market_type': china_market
        }
    )

    if created:
        print("Created Shenzhen Stock Exchange")


def reverse_china_market_data(apps, schema_editor):
    """Reverse the migration if needed"""
    MarketType = apps.get_model('CryptoAnalyst', 'MarketType')
    Exchange = apps.get_model('CryptoAnalyst', 'Exchange')

    # Delete China market data
    Exchange.objects.filter(market_type__name='china').delete()
    MarketType.objects.filter(name='china').delete()
    print("Removed China A-Share market data")


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoAnalyst', '0005_add_china_market_support'),
    ]

    operations = [
        migrations.RunPython(create_china_market_data, reverse_china_market_data),
    ]
