# Generated by Django 4.2.10 on 2025-05-18 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoAnalyst", "0006_delete_marketdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalanalysis",
            name="period_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="technicalanalysis",
            unique_together={("token", "period_start")},
        ),
    ]
