# Generated by Django 4.2.10 on 2025-05-18 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoAnalyst", "0007_technicalanalysis_period_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technicalanalysis",
            name="period_start",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
