# Generated by Django 4.2.10 on 2025-05-21 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_temporaryinvitation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temporaryinvitation",
            name="session_key",
        ),
        migrations.AddField(
            model_name="temporaryinvitation",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="用于认领的唯一标识符",
                unique=True,
            ),
        ),
    ]
