# Generated by Django 4.2.10 on 2025-07-16 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_temporaryinvitation_session_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='套餐名称')),
                ('plan_type', models.CharField(choices=[('monthly', '月付'), ('yearly', '年付')], max_length=10, verbose_name='套餐类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('duration_days', models.IntegerField(verbose_name='有效天数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '会员套餐',
                'verbose_name_plural': '会员套餐',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='是否为高级会员'),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='会员到期时间'),
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', '获得'), ('spend', '消费')], max_length=10, verbose_name='交易类型')),
                ('amount', models.IntegerField(verbose_name='积分数量')),
                ('reason', models.CharField(choices=[('invitation', '邀请好友'), ('premium_analysis', '查看高级分析'), ('admin_adjust', '管理员调整')], max_length=20, verbose_name='原因')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分交易记录',
                'verbose_name_plural': '积分交易记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('expired', '已过期'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='状态')),
                ('payment_method', models.CharField(blank=True, choices=[('alipay', '支付宝'), ('bank_transfer', '银行转账'), ('wechat_friend', '微信好友'), ('other', '其他')], max_length=20, null=True, verbose_name='支付方式')),
                ('payment_info', models.JSONField(blank=True, default=dict, verbose_name='支付信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.membershipplan', verbose_name='套餐')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '会员订单',
                'verbose_name_plural': '会员订单',
                'ordering': ['-created_at'],
            },
        ),
    ]
