# Generated by Django 4.2.10 on 2025-07-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_pointstransaction_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstransaction',
            name='reason',
            field=models.CharField(choices=[('registration', '注册奖励'), ('invitation', '邀请好友'), ('premium_analysis', '查看高级分析'), ('save_image', '保存图片'), ('admin_adjust', '管理员调整')], max_length=20, verbose_name='原因'),
        ),
    ]
